// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};
void loop()
{
  long res;
  memcpy((void*)0x20000240, "/dev/uinput", 12);
  res = syscall(__NR_open, 0x20000240, 2, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000400, "\x23\x00\x00\x01\x21\x40\x8c\x72\xcb\x0e\xfd\xd0"
                            "\x09\xae\xec\x66\x00\xa6\xad\xbb\xe9\x92\x2a\x96"
                            "\xda\x1f\x21\xc2\x32\x40",
         30);
  syscall(__NR_ioctl, r[0], 0x4040105504, 0x20000400);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  loop();
  return 0;
}

