
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

static void test();

void loop()
{
  while (1) {
    test();
  }
}

uint64_t r[1] = {0xffffffffffffffff};
void test()
{
  long res;
  memcpy((void*)0x20000080, "/mnt/f2fs/file0", 16);
  res = syscall(__NR_open, 0x20000080, 0x1212, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000180, "\xe0\x2c\x2a\x5e\x5e\x65\xc3\xb3\x13\xe7\xa0\xa4"
                            "\xbc\x53\x2b\x1f\x4f\xef\x63\x96\x49\xae\x25\x0a"
                            "\x5d\x9d\xc6\x40\x30\x5c",
         30);
  syscall(__NR_write, r[0], 0x20000180, 0xfffffe55);
  memcpy((void*)0x20000000, "/mnt/f2fs/file0", 16);
  syscall(__NR_open, 0x20000000, 0x40, 2);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  for (;;) {
    loop();
  }
}

