// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};
void loop()
{
  long res;
  memcpy((void*)0x20002940, "/dev/pktcdvd/control", 21);
  res = syscall(__NR_open, 0x20002940, 2, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x200003c0, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00",
         30);
  syscall(__NR_ioctl, r[0], 0x40c0185801, 0x200003c0);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  loop();
  return 0;
}

