

// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};
void loop()
{
  long res;
  res = syscall(__NR_socket, 0x1d, 2, 2);
  if (res != -1)
    r[0] = res;
  *(uint16_t*)0x20000000 = 0x1d;
  *(uint32_t*)0x20000004 = 0;
  *(uint32_t*)0x20000008 = 0;
  *(uint32_t*)0x2000000c = 0;
  syscall(__NR_connect, r[0], 0x20000000, 0x10);
  memcpy((void*)0x20000040, "\x05\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\xb5\x00\x00\x09\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\xfd\x9b\x57\x01\x22\xa9\x10"
                            "\xe0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
         72);
  syscall(__NR_write, r[0], 0x20000040, 0x48);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  loop();
  return 0;
}

