// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <unistd.h>

static uintptr_t syz_open_dev(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf));
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(a1 % 10);
      a1 /= 10;
    }
    return open(buf, a2, 0);
  }
}

static void test();

void loop()
{
  while (1) {
    test();
  }
}

uint64_t r[1] = {0xffffffffffffffff};
void test()
{
  long res;
  memcpy((void*)0x20000040, "/dev/input/mice", 16);
  syz_open_dev(0x20000040, 0, 0x200);
  memcpy((void*)0x20000000, "/dev/input/event#", 18);
  res = syz_open_dev(0x20000000, 0x80000401, 0x1000000402);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000080, "\xe7\x0f\x5b\x5c\xc9\x35\x12\x72\xab\x38\x23\xa0"
                            "\x0d\x5b\x11\x68\xcf\x41\x04\xf3\x7f\x00\x96\xc5"
                            "\x77\x7e\x76\x51\x91\xa7\x44\x03\x06\x00\x3a\x00"
                            "\x00\x00\x00\x01\x02\x00\x00\x00\x00\x23\xef\x49",
         48);
  syscall(__NR_write, r[0], 0x20000080, 0x30);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  for (;;) {
    loop();
  }
}

