
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

static void test();

void loop()
{
  while (1) {
    test();
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};
void test()
{
  long res;
  memcpy((void*)0x20000040, "/mnt/f2fs/file0", 16);
  res = syscall(__NR_open, 0x20000040, 0x4102, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x200002c0, "\x90\xca\xd3\xde\x71\x8f\x2e\xf3\x06\x8b\xb8\xf5"
                            "\xbb\x26\xce\x30\x63\x5e\x80\xc5\xe7\x3c\x05\x55"
                            "\x7a\xa8\x8d\x79\xd7\x8d",
         30);
  syscall(__NR_write, r[0], 0x200002c0, 0x1e);
  memcpy((void*)0x20000000, "/mnt/f2fs/file0", 16);
  res = syscall(__NR_open, 0x20000000, 0x102002, 0);
  if (res != -1)
    r[1] = res;
  memcpy((void*)0x20000040, "\xe3\x4b\xf8\x71\x03\x08\x35\xd5\xfe\x87\x0a\xda"
                            "\xbc\x33\x57\x74\x48\x9b\x9a\x0f\x32\x97\xe1\xde"
                            "\xde\x00\x74\x85\x96\xb0",
         30);
  syscall(__NR_write, r[1], 0x20000040, 0x1e);
  memcpy((void*)0x200031c0, "/mnt/f2fs/file0", 16);
  syscall(__NR_open, 0x200031c0, 0x121340, 8);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  for (;;) {
    loop();
  }
}

