// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

static void test();

void loop()
{
  while (1) {
    test();
  }
}

uint64_t r[1] = {0xffffffffffffffff};
void test()
{
  long res;
  memcpy((void*)0x20000180, "/mnt/xfs/file0", 15);
  res = syscall(__NR_open, 0x20000180, 0x80002, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000000, "\x02\x02\x02\x00\x02\x02\x02\x02\x02\x02\x02\x02"
                            "\x02\x02\x02\x21\xde\x13\x63\x6c\xca\x4f\x55\x74"
                            "\xa6\x78\x70\x60\x47\xb6",
         30);
  syscall(__NR_ioctl, r[0], 0x20040305829, 0x20000000);
  memcpy((void*)0x20000180, "/mnt/xfs/file0", 15);
  syscall(__NR_open, 0x20000180, 0x7fffc, 0x22);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  for (;;) {
    loop();
  }
}

