// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <unistd.h>

static uintptr_t syz_open_dev(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf));
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(a1 % 10);
      a1 /= 10;
    }
    return open(buf, a2, 0);
  }
}

static void test();

void loop()
{
  while (1) {
    test();
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};
void test()
{
  long res;
  res = syz_open_dev(0xc, 0x4000004, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000000,
         "\x35\xac\x13\x7a\x31\x20\x50\x7f\x56\x0d\x34\x22\x94\x74\x60\x4d\x88"
         "\xe8\x39\x1a\x83\xd6\x7b\x35\x91\xf0\x1d\x48\xb4\xc6\x9e\x0c\xad\xfa"
         "\xa3\x1e\x89\x87\xb2\xc1\xeb\x4d\x66\xff\xa1\x10\x11\x32\x52\x2f\x66"
         "\x06\x0f\xdc\x12\x2d\x9b\xbf\x7b\x16\x85\x0e\x20\x71\xc7\x46\xd7\x4d"
         "\xea\xc5\x67\xb1\x9f\x95\x9f\xb7\x85\x8e\x44\xc9\x43\x31\x53\xc3\x39"
         "\x96\x60\x19\xf3\x89\xe4\x33\x4d\x86\xd0\xab\x05\x35\xfb\x70\x37\xe9"
         "\x0f\x1e\xe3\x11\x22\x56\x1f\xeb\xa3\x84\xbb\x8e\x89\xf6\x29\x92\xd0"
         "\x7d",
         120);
  syscall(__NR_write, r[0], 0x20000000, 0x78);
  res = syz_open_dev(0xc, 4, 0);
  if (res != -1)
    r[1] = res;
  memcpy((void*)0x20000000, "\x00\x00\x00\x2b\x00\x00\x00\x00\x00\x00\x00\x85"
                            "\xf9\x5a\x78\xe3\xfa\x47\x00\x00",
         20);
  syscall(__NR_ioctl, r[1], 0x400000000560a, 0x20000000);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  for (;;) {
    loop();
  }
}

